import React, { useState, useEffect } from 'react';
import {
  Upload,
  CheckCircle2,
  AlertCircle,
  Code2,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  FileText,
  Clock,
  Download,
  Trash2,
  ChevronRight,
  Target,
  FileSearch
} from 'lucide-react';
import { cn } from '../services/utils';

/* ─────────────────────────────────────────────
   Skill Tag
───────────────────────────────────────────── */
const SkillTag = ({ name, type = 'detected' }) => (
  <span className={cn(
    'px-3 py-1.5 rounded-xl text-[11px] font-black uppercase tracking-wider transition-all',
    type === 'detected'
      ? 'bg-white/5 border border-white/10 text-white/50 hover:bg-white/10 hover:text-white'
      : 'bg-rose-500/10 border border-rose-500/20 text-rose-400'
  )}>
    {name}
  </span>
);

/* ─────────────────────────────────────────────
   Analysis Section Card
───────────────────────────────────────────── */
const AnalysisSection = ({ title, icon: Icon, children, className }) => (
  <div className={cn(
    "bg-[#0c0c14]/60 backdrop-blur-xl border border-white/[0.08] rounded-[2.5rem] p-8 transition-all duration-300 hover:bg-white/[0.04] h-full shadow-2xl flex flex-col group",
    className
  )}>
    <div className="flex items-center gap-4 mb-8 shrink-0">
      <div className="w-12 h-12 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-center text-white/20 shadow-inner group-hover:text-purple-400 group-hover:bg-purple-500/10 transition-all duration-500">
        <Icon size={22} strokeWidth={1.5} />
      </div>
      <h3 className="text-[11px] font-black text-white/30 uppercase tracking-[0.3em]">{title}</h3>
    </div>
    <div className="flex-1 flex flex-col">
      {children}
    </div>
  </div>
);

/* ─────────────────────────────────────────────
   Resume Analyzer Page
───────────────────────────────────────────── */
const ResumeAnalyzer = () => {
  const [file, setFile] = useState(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [hasAnalyzed, setHasAnalyzed] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);

  const careerGoal = "Frontend Architect";

  useEffect(() => {
    if (file && !hasAnalyzed && !isAnalyzing) {
      startAnalysis();
    }
  }, [file, hasAnalyzed, isAnalyzing]);

  const startAnalysis = () => {
    setIsAnalyzing(true);
    setAnalysisProgress(0);
    
    const interval = setInterval(() => {
      setAnalysisProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + 2;
      });
    }, 60);

    setTimeout(() => {
      setIsAnalyzing(false);
      setHasAnalyzed(true);
    }, 3500);
  };

  const handleFileUpload = (f) => {
    if (f) {
      setFile(f);
      setHasAnalyzed(false);
    }
  };

  const handleDownloadReport = () => {
    if (!file) return;
    
    const reportContent = `
SKILLRISE AI - RESUME ANALYSIS REPORT
--------------------------------------
File: ${file.name}
ATS Match Score: 82%
Status: Highly Compatible
Career Path: ${careerGoal}

COMPETENCY STRENGTHS:
- React (85%)
- Node.js (72%)
- TypeScript (64%)

CRITICAL COMPETENCY GAPS:
- Docker
- AWS Cloud
- Jest
- Kubernetes

AI RECOMMENDATIONS:
1. Include measurable performance metrics.
2. Optimize professional summary with role-specific keywords.
3. Highlight Cloud certifications prominently.
4. Consolidate historical roles to optimize space.

Generated by SkillRise AI - ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SkillRise_Report_${file.name.split('.')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full flex flex-col items-center py-6 px-6 md:px-12 lg:px-16 pb-20 relative animate-in fade-in duration-700">
      
      {/* Page header */}
      <div className="w-full max-w-6xl flex flex-col items-center text-center mb-12">
        <h1 className="text-[34px] md:text-[42px] font-black text-white tracking-tight leading-none mb-4">
          Resume <span className="text-white/30 font-light italic">Intelligence</span>
        </h1>
        <p className="text-[14px] md:text-[15px] text-white/40 max-w-2xl leading-relaxed font-medium">
          Upload your professional artifact to quantify your technical presence and identify high-impact competency gaps.
        </p>
      </div>

      {/* Main Interactive Zone */}
      <div className="w-full max-w-6xl">
        
        {!file && !hasAnalyzed ? (
          <div className="space-y-16 animate-in slide-in-from-bottom-8 duration-1000">
            {/* Primary Dropzone (Restored Design) */}
            <div
              onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={(e) => {
                e.preventDefault();
                setIsDragging(false);
                const droppedFile = e.dataTransfer.files[0];
                handleFileUpload(droppedFile);
              }}
              className={cn(
                'relative flex flex-col items-center justify-center w-full min-h-[420px] border-[2px] border-dashed rounded-[3rem] transition-all duration-700 bg-[#0c0c14]/40 backdrop-blur-2xl group cursor-pointer overflow-hidden p-12',
                isDragging
                  ? 'border-purple-500/60 bg-purple-500/10 scale-[1.01] shadow-[0_0_80px_rgba(168,85,247,0.15)]'
                  : 'border-white/[0.06] hover:border-purple-500/30 hover:bg-white/[0.02]'
              )}
            >
              <label className="absolute inset-0 w-full h-full cursor-pointer z-10">
                <input type="file" className="hidden" onChange={(e) => handleFileUpload(e.target.files[0])} accept=".pdf,.docx,.doc" />
              </label>
              <div className="flex flex-col items-center gap-8 pointer-events-none">
                <div className="w-24 h-24 rounded-[2rem] bg-white/[0.02] border border-white/10 flex items-center justify-center text-white/20 group-hover:text-purple-400 group-hover:bg-purple-500/10 group-hover:border-purple-500/30 transition-all duration-500 group-hover:scale-110 shadow-2xl">
                  <Upload size={44} strokeWidth={1.5} />
                </div>
                <div className="text-center space-y-4">
                  <h3 className="text-[28px] md:text-[32px] font-black text-white tracking-tight">Sync Resume Artifact</h3>
                  <p className="text-white/30 text-[14px] font-bold uppercase tracking-[0.3em]">PDF / DOCX Deployment • Max 10MB</p>
                </div>
                <div className="flex items-center justify-center gap-3 px-6 py-2.5 rounded-full bg-white/5 border border-white/10 group-hover:bg-white/10 transition-colors">
                  <ShieldCheck size={16} className="text-emerald-400 opacity-60" />
                  <span className="text-[10px] font-black uppercase tracking-[0.25em] text-white/50">Neural Encryption Enabled</span>
                </div>
              </div>
            </div>

            {/* History Grid (Restored Design) */}
            <div className="space-y-8">
              <div className="flex items-center gap-6 opacity-30">
                <span className="text-[10px] font-black uppercase tracking-[0.5em] text-white whitespace-nowrap">Extraction History</span>
                <div className="h-px bg-white flex-1" />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-20">
                {[
                  { title: "Frontend Lead Role", date: "2d ago", score: "82%", status: "High Sync", color: "text-emerald-400" },
                  { title: "React Dev Pipeline", date: "1w ago", score: "64%", status: "Moderate", color: "text-amber-400" }
                ].map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between p-6 rounded-[2rem] bg-[#0c0c14]/50 border border-white/[0.05] hover:bg-white/[0.03] hover:border-purple-500/20 transition-all cursor-pointer group shadow-xl">
                    <div className="flex items-center gap-5">
                      <div className="w-12 h-12 rounded-2xl bg-white/[0.02] border border-white/5 text-white/20 flex items-center justify-center group-hover:text-purple-400 group-hover:bg-purple-500/10 transition-all">
                        <FileText size={20} />
                      </div>
                      <div className="flex flex-col">
                        <p className="text-[15px] text-white/80 font-bold tracking-tight group-hover:text-white transition-colors">{item.title}</p>
                        <span className="text-[10px] font-black uppercase tracking-[0.2em] text-white/20">{item.date} • {item.status}</span>
                      </div>
                    </div>
                    <div className="flex flex-col items-end">
                      <span className={cn("text-[20px] font-black tracking-tight", item.color)}>{item.score}</span>
                      <span className="text-[9px] font-black uppercase tracking-widest text-white/10">ATS Acc</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : isAnalyzing ? (
          
          <div className="h-full w-full flex flex-col items-center justify-center py-20 animate-in fade-in duration-700">
            <div className="relative w-48 h-48 flex items-center justify-center">
              <div className="absolute inset-0 bg-purple-500/20 rounded-full blur-[40px] animate-pulse" />
              <div className="absolute inset-0 rounded-full border-2 border-transparent border-t-purple-400 animate-[spin_1.5s_linear_infinite]" />
              <div className="absolute inset-4 rounded-full border-2 border-transparent border-b-cyan-400 animate-[spin_2s_linear_infinite_reverse]" />
              <div className="w-16 h-16 bg-[#0a0a0f] rounded-full flex items-center justify-center z-10 border border-white/10">
                  <Sparkles className="text-purple-400 animate-pulse" size={28} />
              </div>
            </div>
            <div className="mt-12 flex flex-col items-center gap-6">
              <h3 className="text-[28px] font-black text-white tracking-widest uppercase italic animate-pulse">Analyzing</h3>
              <div className="w-64 h-1.5 bg-white/5 rounded-full overflow-hidden border border-white/5">
                <div className="h-full bg-gradient-to-r from-purple-600 via-indigo-500 to-cyan-500 transition-all duration-300" style={{ width: `${analysisProgress}%` }} />
              </div>
            </div>
          </div>

        ) : hasAnalyzed && file ? (

          <div className="w-full flex flex-col gap-8 animate-in slide-in-from-bottom-8 duration-700">
            
            {/* Sync Status Bar */}
            <div className="flex flex-col md:flex-row items-center justify-between bg-[#0b0b12]/60 border border-white/[0.08] p-6 rounded-[2.5rem] backdrop-blur-xl gap-6 shadow-2xl">
              <div className="flex items-center gap-6">
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-500/20 to-indigo-500/20 text-emerald-400 flex items-center justify-center border border-emerald-500/20 shadow-inner">
                  <CheckCircle2 size={32} />
                </div>
                <div>
                  <p className="text-white font-black text-[18px] tracking-tight">{file.name}</p>
                  <p className="text-white/30 text-[10px] font-black uppercase tracking-[0.2em] mt-1">Intelligence Synchronized • {(file.size/1024/1024).toFixed(2)} MB PDF</p>
                </div>
              </div>
              <button 
                onClick={() => { setFile(null); setHasAnalyzed(false); }} 
                className="px-8 py-4 rounded-xl bg-white/5 hover:bg-white/10 text-white/50 hover:text-white font-black text-[11px] uppercase tracking-widest transition-all border border-white/5 active:scale-95"
              >
                Launch New Cycle
              </button>
            </div>

            {/* RESULTS GRID (3-Column Architecture) */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 pb-10">
              
              {/* Card 1: Scoring Hero */}
              <AnalysisSection title="Match Score" icon={Sparkles}>
                <div className="flex flex-col items-center justify-between h-full pt-4">
                  <div className="relative w-48 h-48 flex items-center justify-center">
                    <svg className="absolute inset-0 w-full h-full transform -rotate-90">
                      <circle cx="96" cy="96" r="86" fill="transparent" stroke="rgba(255,255,255,0.03)" strokeWidth="16" />
                      <circle cx="96" cy="96" r="86" fill="transparent" stroke="url(#ats-grad)" strokeWidth="16" strokeLinecap="round" strokeDasharray="540" strokeDashoffset={540 * (1 - 0.82)} className="transition-all duration-[2000ms] drop-shadow-[0_0_20px_rgba(168,85,247,0.4)]" />
                      <defs>
                        <linearGradient id="ats-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#a786ff" />
                          <stop offset="100%" stopColor="#60a5fa" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <span className="text-[64px] font-black text-white tracking-tighter">82</span>
                  </div>
                  
                  <div className="text-center space-y-4 mb-8">
                    <h4 className="text-[20px] font-black text-white tracking-tight">Heavy Sync</h4>
                    <p className="text-[14px] text-white/40 font-medium leading-relaxed">
                      Logic structure aligns with <span className="text-white/60">{careerGoal}</span> standards. Threshold reached for evaluation.
                    </p>
                  </div>

                  <button 
                    onClick={handleDownloadReport}
                    className="w-full py-5 rounded-2xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-black text-[12px] uppercase tracking-widest shadow-xl hover:brightness-110 transition-all flex items-center justify-center gap-4 group"
                  >
                    <Download size={18} className="group-hover:-translate-y-1 transition-transform" />
                    Transmit Report
                  </button>
                </div>
              </AnalysisSection>

              {/* Card 2: Competency Breakdown */}
              <AnalysisSection title="Competency" icon={Target}>
                <div className="space-y-10 py-4">
                  <div className="space-y-8">
                    {[
                      { l: 'Architecture', v: 85, c: 'bg-purple-500' },
                      { l: 'Backend Sync', v: 72, c: 'bg-indigo-500' },
                      { l: 'Neural Logic', v: 64, c: 'bg-blue-500' }
                    ].map((s, i) => (
                      <div key={i} className="space-y-3">
                        <div className="flex justify-between items-end">
                          <span className="text-[13px] font-black text-white/70 uppercase tracking-wider">{s.l}</span>
                          <span className="text-[10px] font-black text-white/20">{s.v}%</span>
                        </div>
                        <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
                          <div className={cn("h-full transition-all duration-[2000ms]", s.c)} style={{ width: `${s.v}%` }} />
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="pt-8 border-t border-white/[0.05]">
                    <p className="text-[10px] font-black uppercase tracking-widest text-white/20 mb-6">Identified Gaps</p>
                    <div className="flex flex-wrap gap-2.5">
                      {['Docker', 'AWS', 'Jest', 'Kubernetes'].map(g => <SkillTag key={g} name={g} type="gap" />)}
                    </div>
                  </div>
                </div>
              </AnalysisSection>

              {/* Card 3: AI Optimization Feed */}
              <AnalysisSection title="Optimization" icon={AlertCircle}>
                <div className="flex flex-col gap-6 py-4">
                  {[
                    'Include measurable performance metrics (e.g., "Scaled logic by 40%").',
                    'Synchronize summary with role-specific keywords.',
                    'Prioritize technical certifications in header.',
                    'Prune historical artifacts beyond 10-year threshold.'
                  ].map((t, i) => (
                    <div key={i} className="bg-white/[0.02] border border-white/[0.05] rounded-[1.5rem] p-5 flex gap-4 items-start group hover:bg-white/[0.04] transition-all">
                      <div className="w-6 h-6 rounded-lg bg-white/5 flex items-center justify-center shrink-0 text-[10px] font-black text-white/20 group-hover:text-purple-400 transition-colors">
                        0{i+1}
                      </div>
                      <p className="text-[14px] text-white/50 leading-relaxed font-medium group-hover:text-white/80 transition-colors">{t}</p>
                    </div>
                  ))}
                </div>
              </AnalysisSection>

            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
};

export default ResumeAnalyzer;
