// LangGraph - Agentic Chatbot Orchestrator
// Coordinates the multi-step agent workflow using LangGraph's StateGraph.
// FLOW: START → Router → RetrieverNode → [Agents...] → Aggregator → ResponseGenerator → END

const { StateGraph, START, END } = require("@langchain/langgraph");

// Import all agents
const routerAgent = require("../agents/routerAgent");
const retrieverNode = require("../agents/retrieverNode");
const resumeAgent = require("../agents/resumeAgent");
const careerAgent = require("../agents/careerAgent");
const skillAgent = require("../agents/skillAgent");
const schemeAgent = require("../agents/schemeAgent");
const roadMapAgent = require("../agents/roadmapAgent");
const aggregator = require("./responseAggregator");
const responseGenerator = require("../agents/responseGenerator");

/**
 * Define the graph state structure.
 * This defines the channels and the shape of the data that will be passed between nodes.
 * We accumulate all processed information in the 'data' key to enforce the JSON structure.
 */
const graphState = {
  // Global Identifiers
  threadId: { value: (x, y) => y ? y : x, default: () => null },
  
  // Inputs from user interaction/upload
  resumeFilePath: { value: (x, y) => y ? y : x, default: () => null },
  userQuery: { value: (x, y) => y ? y : x, default: () => "" },
  userProfile: { value: (x, y) => y ? y : x, default: () => null },
  selectedAgents: { value: (x, y) => y ? y : x, default: () => [] },
  
  // Dataset selection from routerAgent (which Pinecone datasets to query)
  datasets: { value: (x, y) => y ? y : x, default: () => [] },
  
  // Retrieved data from Pinecone (populated by retrieverNode)
  retrievedData: { 
    value: (x, y) => y ? { ...x, ...y } : x, 
    default: () => ({}) 
  },

  // Memory Contexts injected for reasoning logic
  chatHistory: { value: (x, y) => y ? y : x, default: () => [] },
  semanticContext: { value: (x, y) => y ? y : x, default: () => [] },
  datasetContext: { value: (x, y) => y ? y : x, default: () => [] },

  // Global Agent status fields
  status: { value: (x, y) => y ? y : x, default: () => "idle" },
  source: { value: (x, y) => y ? y : x, default: () => null },
  reasoning: { value: (x, y) => y ? y : x, default: () => null },
  error: { value: (x, y) => y ? y : x, default: () => null },
  userContext: { value: (x, y) => Object.keys(y || {}).length ? y : x, default: () => ({}) },
  userPreferences: { value: (x, y) => Object.keys(y || {}).length ? y : x, default: () => ({}) },

  // The unified data object where all agents output their findings
  data: { 
    value: (x, y) => ({ ...x, ...y }), 
    default: () => ({}) 
  },
  
  // Final aggregated response from responseAggregator
  finalResponse: { value: (x, y) => y ? y : x, default: () => null },
  
  // Human-like response generated by responseGenerator
  conversationalResponse: { value: (x, y) => y ? y : x, default: () => "" }
};

// Create the LangGraph state graph
const workflow = new StateGraph({
  channels: graphState
});

// Add nodes for each agent
workflow.addNode("router", routerAgent);
workflow.addNode("retrieverNode", retrieverNode);
workflow.addNode("resumeAgent", resumeAgent);
workflow.addNode("careerAgent", careerAgent);
workflow.addNode("skillAgent", skillAgent);
workflow.addNode("schemeAgent", schemeAgent);
workflow.addNode("roadMapAgent", roadMapAgent);
workflow.addNode("aggregator", aggregator);
workflow.addNode("responseGenerator", responseGenerator);

// ═══════════════════════════════════════════════════════════════════════════════
// Define the workflow edges (Execution pipeline)
// NEW FLOW: Router → RetrieverNode → Agents → Aggregator → ResponseGenerator
// ═══════════════════════════════════════════════════════════════════════════════

// Connect the special START node to the router agent
workflow.addEdge(START, "router");

// After routing, ALWAYS run the retriever to fetch RAG context
// (except for chitchat — handled inside retrieverNode which returns empty data)
workflow.addEdge("router", "retrieverNode");

// Dynamic routing FROM retrieverNode to the appropriate agents
workflow.addConditionalEdges(
  "retrieverNode",
  (state) => {
    // If resumeAgent is selected, enforce it runs first sequentially to populate userSkills
    if (state.selectedAgents.includes("resumeAgent")) {
      return ["resumeAgent"]; 
    }
    
    // If other functional agents are selected (excluding chitchat)
    const functionalAgents = state.selectedAgents.filter(a => a !== "chitchat");
    if (functionalAgents.length > 0) return functionalAgents;
    
    if (state.selectedAgents.includes("chitchat")) return ["responseGenerator"];
    
    return ["responseGenerator"];
  },
  {
    resumeAgent: "resumeAgent",
    careerAgent: "careerAgent",
    skillAgent: "skillAgent",
    schemeAgent: "schemeAgent",
    roadMapAgent: "roadMapAgent",
    responseGenerator: "responseGenerator"
  }
);

// Sequence remainder of agents after resume parsing
workflow.addConditionalEdges(
  "resumeAgent",
  (state) => {
    const remainingAgents = state.selectedAgents.filter(a => a !== "resumeAgent" && a !== "chitchat");
    if (remainingAgents.length > 0) {
      return remainingAgents;
    }
    return ["aggregator"];
  },
  {
    careerAgent: "careerAgent",
    skillAgent: "skillAgent",
    schemeAgent: "schemeAgent",
    roadMapAgent: "roadMapAgent",
    aggregator: "aggregator"
  }
);
workflow.addEdge("careerAgent", "aggregator");
workflow.addEdge("skillAgent", "aggregator");
workflow.addEdge("schemeAgent", "aggregator");
workflow.addEdge("roadMapAgent", "aggregator");

// Connect the aggregator to the conversational response generator
workflow.addEdge("aggregator", "responseGenerator");

// Connect the final node to the special END node
workflow.addEdge("responseGenerator", END);

// Compile the graph into an executable format with conversational memory (checkpointer)
const { MemorySaver } = require("@langchain/langgraph");
const checkpointer = new MemorySaver();
const app = workflow.compile({ checkpointer });

// Export the compiled graph implementation
module.exports = app;
