/**
 * Response Aggregator Node for LangGraph
 * Collects results generated by all executed agents and returns a single structured response.
 * Includes richer context: resume info, skill analysis, career data, and courses.
 */
async function responseAggregator(state) {
  console.log("--- RESPONSE AGGREGATOR EXECUTION ---");
  
  // Data accumulated from agents modifying state.data in prior steps
  const data = state.data || {};

  const response = {
    // Resume information
    resumeInfo: data.resumeAnalysis || null,

    // Career recommendations and job roles
    careerRecommendations: data.careerRecommendations || state.careerRecommendations || null,
    targetRole: data.targetRole || state.targetRole || null,

    // Skill gap analysis with learning roadmap
    skillAnalysis: data.skillAnalysis || data.skillMatchResult || state.skillAnalysis || state.skillMatchResult || null,

    // Recommended courses
    courses: data.recommendedCourses || state.recommendedCourses || null,

    // Government schemes
    governmentSchemes: data.schemeRecommendations || state.schemeRecommendations || null,

    // Custom roadmap from roadmapAgent
    roadmap: data.roadmap || state.roadmap || null,
  };
  
  // Filter out any null / empty fields
  const cleanedResponse = Object.fromEntries(
    Object.entries(response).filter(([_, v]) => {
      if (v == null) return false;
      if (Array.isArray(v) && v.length === 0) return false;
      if (typeof v === 'object' && !Array.isArray(v) && Object.keys(v).length === 0) return false;
      return true;
    })
  );

  console.log(`[ResponseAggregator] Response keys: ${Object.keys(cleanedResponse).join(', ') || '(empty)'}`);

  return {
    finalResponse: cleanedResponse
  };
}

module.exports = responseAggregator;
